"""auto generate votes table

Revision ID: 286e46c803ee
Revises: 3e1520c0ea14
Create Date: 2023-02-22 05:10:13.580469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '286e46c803ee'
down_revision = '3e1520c0ea14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    # op.add_column('users', sa.Column('joined', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False))
    # op.drop_column('users', 'created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # op.drop_column('users', 'joined')
    op.drop_table('votes')
    # ### end Alembic commands ###
