"""add content column to posts table

Revision ID: 46277d5506d3
Revises: db49c1a93afa
Create Date: 2023-06-13 00:40:59.088012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46277d5506d3'
down_revision = 'db49c1a93afa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_name', sa.String(), nullable=False),
    sa.Column('show_air_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW(), INTERVAL 1 DAY'), nullable=False),
    sa.Column('show_end_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW(), INTERVAL 1 DAY, INTERVAL 1 HOUR'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('member', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('writer', sa.String(), nullable=True),
    sa.Column('editor', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('mos_objects', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('last_modified_by', sa.String(), nullable=False),
    sa.Column('estimated_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.add_column('posts', sa.Column('content', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('published', sa.Boolean(), server_default='TRUE', nullable=False))
    op.add_column('posts', sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False))
    op.add_column('posts', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'posts', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'owner_id')
    op.drop_column('posts', 'created')
    op.drop_column('posts', 'published')
    op.drop_column('posts', 'content')
    op.drop_table('votes')
    op.drop_table('stories')
    op.drop_table('users')
    op.drop_table('shows')
    # ### end Alembic commands ###
